// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");

var letters = [
  "a",
  "b",
  "c"
];

var x = Belt_Array.get(letters, 10);

console.log(x === undefined);

var y = Belt_Array.get(letters, 0);

console.log(y !== undefined ? y.toUpperCase() : "");

exports.letters = letters;
exports.x = x;
/* x Not a pure module */
